-----------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_USUARIO (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(100) NOT NULL,
    email      VARCHAR2(100) NOT NULL UNIQUE,
    senha      VARCHAR2(255) NOT NULL,
    role       VARCHAR2(20)  NOT NULL CHECK (role IN ('PACIENTE','PROFISSIONAL')),
    criado_em  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
---------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_PACIENTE (
    id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario  NUMBER NOT NULL UNIQUE,
    cpf         VARCHAR2(11)  NOT NULL UNIQUE,
    sexo        CHAR(1) DEFAULT NULL CHECK (sexo IN ('M','F')),
    dt_nascimento DATE NOT NULL,
    telefone    VARCHAR2(15),
    cidade      VARCHAR2(100),
    status      VARCHAR2(20) DEFAULT 'ATIVO' CHECK (status IN ('ATIVO','INATIVO')),
    CONSTRAINT fk_paciente_usuario FOREIGN KEY (id_usuario)
        REFERENCES T_TDSPW_PGR_USUARIO(id_usuario)
);

---------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_TIPO_PROFISSIONAL_SAUDE (
    id_tipo_profissional NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_tipo            VARCHAR2(100) NOT NULL UNIQUE
);

---------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_PROFISSIONAL_SAUDE (
    id_profissional     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          NUMBER NOT NULL UNIQUE,
    id_tipo_profissional NUMBER NOT NULL,
    crm                 VARCHAR2(20) UNIQUE,
    status              VARCHAR2(20) DEFAULT 'ATIVO' CHECK (status IN ('ATIVO','INATIVO')),
    CONSTRAINT fk_profissional_usuario FOREIGN KEY (id_usuario)
        REFERENCES T_TDSPW_PGR_USUARIO(id_usuario),
    CONSTRAINT fk_profissional_tipo FOREIGN KEY (id_tipo_profissional)
        REFERENCES T_TDSPW_PGR_TIPO_PROFISSIONAL_SAUDE(id_tipo_profissional)
);
---------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_DISPONIBILIDADE (
    id_disponibilidade  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profissional     NUMBER NOT NULL,
    data_hora           TIMESTAMP NOT NULL,
    status              VARCHAR2(20) DEFAULT 'LIVRE' CHECK (status IN ('LIVRE','RESERVADA')),
    criado_em           TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_disponibilidade_profissional FOREIGN KEY (id_profissional)
        REFERENCES T_TDSPW_PGR_PROFISSIONAL_SAUDE(id_profissional),
    CONSTRAINT uk_disponibilidade_profissional_data UNIQUE (id_profissional, data_hora)
);
---------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_CONSULTA (
    id_consulta          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente          NUMBER NOT NULL,
    id_profissional      NUMBER NOT NULL,
    id_disponibilidade   NUMBER NOT NULL,
    id_usuario_agendador NUMBER,
    data_hora            TIMESTAMP NOT NULL,
    tipo_consulta        VARCHAR2(20) NOT NULL CHECK (tipo_consulta IN ('PRESENCIAL','TELECONSULTA')),
    link_acesso          VARCHAR2(255),
    status               VARCHAR2(20) DEFAULT 'AGENDADA' CHECK (status IN ('AGENDADA','REALIZADA','CANCELADA','FALTOU')),
    criado_em            TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (id_paciente)
        REFERENCES T_TDSPW_PGR_PACIENTE(id_paciente),
    CONSTRAINT fk_consulta_profissional FOREIGN KEY (id_profissional)
        REFERENCES T_TDSPW_PGR_PROFISSIONAL_SAUDE(id_profissional),
    CONSTRAINT fk_consulta_disponibilidade FOREIGN KEY (id_disponibilidade)
        REFERENCES T_TDSPW_PGR_DISPONIBILIDADE(id_disponibilidade),
    CONSTRAINT fk_consulta_agendador FOREIGN KEY (id_usuario_agendador)
        REFERENCES T_TDSPW_PGR_USUARIO(id_usuario)
);

---------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_MENSAGEM_AUTOMATICA (
    id_mensagem   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta   NUMBER NOT NULL,
    horario_envio TIMESTAMP NOT NULL,
    tipo_mensagem VARCHAR2(30) CHECK (tipo_mensagem IN ('LEMBRETE_24H','LEMBRETE_3H','LEMBRETE_1H','CONFIRMACAO','AGRADECIMENTO')),
    conteudo      VARCHAR2(255),
    CONSTRAINT fk_mensagem_consulta FOREIGN KEY (id_consulta)
        REFERENCES T_TDSPW_PGR_CONSULTA(id_consulta)
);

---------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_FEEDBACK_CONSULTA (
    id_feedback NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta NUMBER NOT NULL,
    nota        NUMBER CHECK (nota BETWEEN 1 AND 5),
    comentario  VARCHAR2(255),
    criado_em   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_feedback_consulta FOREIGN KEY (id_consulta)
        REFERENCES T_TDSPW_PGR_CONSULTA(id_consulta)
);

--------------------------------------------------------------------
CREATE TABLE T_TDSPW_PGR_ACESSO_TELECONSULTA (
    id_acesso   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta NUMBER NOT NULL,
    horario_acesso TIMESTAMP DEFAULT SYSTIMESTAMP,
    resultado   VARCHAR2(50),
    CONSTRAINT fk_acesso_consulta FOREIGN KEY (id_consulta)
        REFERENCES T_TDSPW_PGR_CONSULTA(id_consulta)
);

 ------------------------------------------------------------
CREATE OR REPLACE VIEW VW_CONSULTAS_PUBLICAS AS
SELECT 
    c.id_consulta,
    p.id_paciente,
    p.cpf,
    pu.nome AS nome_paciente,
    pr.id_profissional,
    pr.crm,
    tp.nome_tipo AS especialidade,
    pru.nome AS nome_profissional,
    c.data_hora,
    c.tipo_consulta,
    c.status,
    CASE WHEN c.tipo_consulta = 'TELECONSULTA' THEN c.link_acesso END AS link_acesso
FROM T_TDSPW_PGR_CONSULTA c
JOIN T_TDSPW_PGR_PACIENTE p ON p.id_paciente = c.id_paciente
JOIN T_TDSPW_PGR_USUARIO pu ON pu.id_usuario = p.id_usuario
JOIN T_TDSPW_PGR_PROFISSIONAL_SAUDE pr ON pr.id_profissional = c.id_profissional
JOIN T_TDSPW_PGR_USUARIO pru ON pru.id_usuario = pr.id_usuario
JOIN T_TDSPW_PGR_TIPO_PROFISSIONAL_SAUDE tp ON tp.id_tipo_profissional = pr.id_tipo_profissional;
