------------------------------------------------------------
-- DROP
------------------------------------------------------------
DROP VIEW VW_CONSULTAS_PUBLICAS;
DROP TABLE T_TDSPW_PGR_ACESSO_TELECONSULTA CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_FEEDBACK_CONSULTA CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_MENSAGEM_AUTOMATICA CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_CONSULTA CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_DISPONIBILIDADE CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_PROFISSIONAL_SAUDE CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_TIPO_PROFISSIONAL_SAUDE CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_PACIENTE CASCADE CONSTRAINTS;
DROP TABLE T_TDSPW_PGR_USUARIO CASCADE CONSTRAINTS;
